[package]
name = "grass-latte-server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
derive-getters = "0.5.0"
grass-latte = {path = "../grass-latte-rs"}
